// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxhkxvkgfxokffxobvph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aGt4dmtnZnhva2ZmeG9idnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDUxOTksImV4cCI6MjA2MTAyMTE5OX0.P8QFQf3_cmgGKCi9kIYiBEbDhyoTN6o863W4J-Iwaak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);